language: python
python:
  - "3.6"
install:
  - "pip install --upgrade pip"
  - "pip install -e --upgrade --no-cache .[dev]"
  - "flask adduser -u admin -p 1234"
script:
  - "flake8 talkshow/"
  - "flake8 tests/"
  - "py.test  -v --cov-config .coveragerc --cov=talkshow -l --tb=short --maxfail=1 tests/"
after_success: codecov
